language: node_js
notifications:
  email: false
services:
  - docker
cache:
  directories:
  - node_modules
node_js:
  - '8'
after_success:
  - npm run deploy
# Trigger a push build on master and khulnasoft branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^khulnasoft.*$/
